### ISSUE TITLE
Error installing diff-gaussian-rasterization-softmax

### ISSUE THREAD

**Issue by nurbanu170399** [ForMyCat/SparseGS#17]
I have been trying to install all the dependencies. Only diff-gaussian-rasterization-softmax submodule is problematic. I have cuda 11.8 installed in my 22.04 ubuntu system, and when i do `pip install diff-gaussian-rasterization-softmax ` i get the following error:
`Processing ./submodules/diff-gaussian-rasterization-softmax
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-310/diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/pc_5053/SparseGS/submodules/diff-gaussian-rasterization-softmax/setup.py", line 16, in <module>
          setup(
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 518, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/pc_5053/anaconda3/envs/SparseGS2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.4). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: Could not build wheels for diff_gaussian_rasterization, which is required to install pyproject.toml-based projects`
It claims that I have pytorch compiled with cuda 12.4, but i dont have cuda 12.4. I dont understand how this is possible. How can i fix it? Thanks in advance.

**Comment by destroy314** [comment]
looks like you need to install a wheel which is compiled with cuda 11.8:
`pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118`
or other versions here https://pytorch.org/get-started/previous-versions/

**Comment by nurbanu170399** [comment]
Thanks for the reply. I installed 
`pip install torch-2.1.0+cu118 torchaudio-2.1.0+cu118 torchvision-0.16.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html`
And i was able to install diff-gaussian-rasterization-softmax after this. Now i get cuda out of memory error during training in diff-gaussian-rasterization. Did i do something wrong? Need some help here.

**Comment by micky-li-hd** [comment]
you can change your graphic card to solve out of memory
