### ISSUE TITLE
how can i solute it?

### ISSUE THREAD

**Issue by Mrsunhaipeng** [ForMyCat/SparseGS#23]
Need your help!
(gaussian_splatting) PS E:\BaiduSyncdisk\Project\SparseGS-master> python train.py --source_path data/art --model_path output/art --beta 5.0 --lambda_pearson 0.05 --lambda_local_pearson 0.15 --box_p 128 --p_corr 0.5 --lambda_diffusion 0.001 --SDS_freq 0.1 --step_ratio 0.99 --lambda_reg 0.1 --prune_sched 20000 --prune_perc 0.98 --prune_exp 7.5 --iterations 30000 --checkpoint_iterations 30000 -r 2
Optimizing output/art
Output folder: output/art [18/09 11:05:08]
Tensorboard Found! [18/09 11:05:08]
Reading camera 43/43Loading Training Cameras [18/09 11:05:08]
Loading Test Cameras [18/09 11:05:13]
Number of points at initialisation : 5550 [18/09 11:05:13]
Training progress: 0%| | 0/30000 [00:00<?, ?it/s][20000] [18/09 11:05:13]
urllib3.exceptions.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "D:\miniconda3\envs\gaussian_splatting\lib\site-packages\requests\adapters.py", line 497, in send
chunked=chunked,
File "D:\miniconda3\envs\gaussian_splatting\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
File "D:\miniconda3\envs\gaussian_splatting\lib\site-packages\urllib3\util\retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-2-1-base (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))

During handling of the above exception, another exception occurred:

**Comment by Mrsunhaipeng** [comment]
maybe because i run it on windows?

**Comment by ForMyCat** [comment]
Looks like a huggingface error. Try to disable the SDS loss. On Sep 18, 2024, at 01:09, Mrsunhaipeng ***@***.***> wrote:﻿
maybe because i run it on windows?

**Comment by Mrsunhaipeng** [comment]
I set lambda_diffusion=0,and it brings another issues.
 (gaussian_splatting) (base) shp@shp-DL:~/Project/SparseGS-master$ python3 train.py --source_path data/art --model_path output/art --beta 5.0 --lambda_pearson 0.05 --lambda_local_pearson 0.15 --box_p 128 --p_corr 0.5 --lambda_diffusion 0 --SDS_freq 0 --step_ratio 1 --lambda_reg 0 --prune_sched 2000
0 --prune_perc 0.98 --prune_exp 7.5 --iterations 30000 --checkpoint_iterations 30000 -r 2
Optimizing output/art
Output folder: output/art [19/09 21:20:16]
Tensorboard not available: not logging progress [19/09 21:20:16]
Reading camera 43/43Loading Training Cameras [19/09 21:20:16]
Loading Test Cameras [19/09 21:20:17]
Number of points at initialisation :  5550 [19/09 21:20:17]
Training progress:   0%|                                                                                                   | 0/30000 [00:00<?, ?it/s][20000] [19/09 21:20:17]
Traceback (most recent call last):
  File "train.py", line 459, in <module>
    training(dataset, op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.step, args.max_cameras, args.prune_sched)
  File "train.py", line 135, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/shp/Project/SparseGS-master/gaussian_renderer/__init__.py", line 39, in render
    ret_pts=ret_pts
TypeError: __new__() got an unexpected keyword argument 'beta'
Training progress:   0%|                                                                                                   | 0/30000 [00:00<?, ?it/s]

**Comment by Mrsunhaipeng** [comment]
@ForMyCat

**Comment by ForMyCat** [comment]
Hi, did you install our softmax depth rasterizer? Please try "pip install
submodules/diff-gaussian-rasterization-softmax".

**Comment by Mrsunhaipeng** [comment]
@ForMyCat ,Thanks you,I have successfully installed my environment.I rendered it,and got the files (depth,gt,modes,renders...), all i saw in renders is the png...What I want to know is how do I visualize it just like 3DGS? Or export the model or anything

**Comment by ForMyCat** [comment]
Please check the SIBR Viewer section from the original 3DGS codebase. You can visualize SparseGS the same way. On Sep 21, 2024, at 03:06, Mrsunhaipeng ***@***.***> wrote:﻿
@ForMyCat ,Thanks you,I have successfully installed my environment.I rendered it,and got the files (depth,gt,modes,renders...), all i saw in renders is the png...What I want to know is how do I visualize it just like 3DGS? Or export the model or anything

**Comment by Mrsunhaipeng** [comment]
@ForMyCat Thank you for your answer, the most important thing now for the understanding of your model is the SDS, which I've now downloaded manually
[stabilityai/stable-diffusion-2-1-base](https://huggingface.co/stabilityai/stable-diffusion-2-1-base) file, but it still seems to report errors, can you talk to me about how you use it? What directory should I put this in to use this?  Appreciate it if you can let me know

**Comment by Mrsunhaipeng** [comment]
OSError: Cannot load model stabilityai/stable-diffusion-2-1-base: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
Training progress:   0%|                                                 | 0/30000 [02:10<?, ?it/s]
